- name: Download Docker Install Script
  get_url:
    url: https://get.docker.com
    dest: /tmp/get-docker.sh

- name: Install Docker
  shell: sh /tmp/get-docker.sh
  become: yes

- name: Install Docker Compose
  apt:
    name: docker-compose
    state: present
  become: yes

- name: Add Current User to Docker Group
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    state: present
    append: yes
  become: yes