- name: Install NGINX
  apt:
    name: nginx
    state: present
  become: yes

- name: Setting Up Default VirtualHost
  template:
    src: templates/default
    dest: /etc/nginx/sites-available/default
  notify:
    - Restart NGINX
  become: yes

  