- name: Add Vagrant GPG Key
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present
  become: yes

- name: Add Vagrant Repo
  apt_repository:
    repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
  become: yes

- name: Install Vagrant
  apt:
    name: vagrant
    update_cache: yes
  become: yes