# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  config.vm.define "mysql" do |mysql|
    config.vm.network "private_network", ip: "10.10.10.21"  
    config.vm.hostname = "mysql"
    
    config.vm.provider "virtualbox" do |vb|
      vb.name = "mysql"
      vb.memory = "1024"
      vb.cpus = 2
      vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
    end  
  end
end
