# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.define "app" do |app|
    app.vm.network "private_network", ip: "10.10.10.30"  
    app.vm.hostname = "app"
    
    app.vm.provider "virtualbox" do |vb|
      vb.memory = "256"
      vb.cpus = 1
      vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
    end
  end
  
  config.vm.define "mysql" do |mysql|
    mysql.vm.network "private_network", ip: "10.10.10.31"  
    mysql.vm.hostname = "mysql"
    
    mysql.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
      vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
    end
  end
end
