- name: Install VirtualBox Dependencies
  apt:
    name:
      - gcc
      - make
      - perl
    state: present
    cache_valid_time: 60
    update_cache: yes
  become: yes

- name: Check if VirtualBox is already Installed
  stat:
    path: /opt/VirtualBox
  register: virtualbox_installed

- name: Download VirtualBox Install Script
  get_url:
    url: https://download.virtualbox.org/virtualbox/6.1.30/VirtualBox-6.1.30-148432-Linux_amd64.run
    dest: /tmp/virtualbox.run
    timeout: 600
  when: not virtualbox_installed.stat.exists

- name: Install VirtualBox
  shell: sh /tmp/virtualbox.run
  become: yes    
  when: not virtualbox_installed.stat.exists

- name: Remove VirtualBox Install Script
  file:
    path: /tmp/virtualbox.run
    state: absent